[[Cubature]]
arch = "aarch64"
git-tree-sha1 = "37c472fcfe7b287aa4cf16a7d58c9f17a0d7b9b5"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "e91690f9a35cb717901d94581290ea2ee4916c6357bf030c3eb54b267cc2e103"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.aarch64-linux-gnu.tar.gz"
[[Cubature]]
arch = "aarch64"
git-tree-sha1 = "1a0af0c448b7f0748e103bdd957eadc4dd6d2997"
libc = "musl"
os = "linux"

    [[Cubature.download]]
    sha256 = "71351b250ee7837624edbadfd52219d281e296d37ce5f775b95fd546d150f935"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.aarch64-linux-musl.tar.gz"
[[Cubature]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a50a2167bcd681f9f4b6762b8439b05d36c2311b"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "96dd8b92c36f34d40510fe18ea4f834ac66385cc87b3cee7e6b442cc857a4d47"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.armv7l-linux-gnueabihf.tar.gz"
[[Cubature]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9b77440da2c2a5cc97d6d16655c69ffe156bc2ff"
libc = "musl"
os = "linux"

    [[Cubature.download]]
    sha256 = "8ca7758334200ef0488012124fece52b7aed4490597291f55c62ec72fbf606d2"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.armv7l-linux-musleabihf.tar.gz"
[[Cubature]]
arch = "i686"
git-tree-sha1 = "23b1b2dc1b8a37c63767678718f068d19f8cea83"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "ba8f60f7c09bcebbe0280918a8387771368272ff6a959cfd4cca55b8298bb2b8"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.i686-linux-gnu.tar.gz"
[[Cubature]]
arch = "i686"
git-tree-sha1 = "25e40dae5593cfabdd8b6c8115e08be955c2e5aa"
libc = "musl"
os = "linux"

    [[Cubature.download]]
    sha256 = "bfa318c496fedf2d02ff7e2eafd2672e2a67118802dc0de34e352c25559dbb07"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.i686-linux-musl.tar.gz"
[[Cubature]]
arch = "i686"
git-tree-sha1 = "77a82330002c9316f7b3eb2e86b1563a365bf0e6"
os = "windows"

    [[Cubature.download]]
    sha256 = "22b3aac27960484f13c0aeeb258dfc98fbbdc4abe4dc45d0bdd64aee82472d03"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.i686-w64-mingw32.tar.gz"
[[Cubature]]
arch = "powerpc64le"
git-tree-sha1 = "bb94f9752c428aef30e63c80dce891cc499912cb"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "f592d842ac0b171d81d0d4f478a420e0b8b767a56bf7fb9f38dc27241cf59cfd"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.powerpc64le-linux-gnu.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "be93c8af410f0b1c3ad3a9f0a1f07a45dfe2e241"
os = "macos"

    [[Cubature.download]]
    sha256 = "d864bbf64b80e2a47550b9b66ae524cfe90e2dca76093ee4bb159ef6d09dec15"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.x86_64-apple-darwin.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "8d2ea3039759488889cac1c76b1bc7db87eeb62e"
libc = "glibc"
os = "linux"

    [[Cubature.download]]
    sha256 = "00afe25d07f5b8b51bcc69b4e04e3626dac6b3f43b87d5a4a0d1832612525500"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.x86_64-linux-gnu.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "84d89a6c093ca9050f3a8d1c713bd4050b62662d"
libc = "musl"
os = "linux"

    [[Cubature.download]]
    sha256 = "c01e4849589d1766a789463e32a1b92f93adc7ddbe289d5f1e70607c9dfad89e"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.x86_64-linux-musl.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "e52f416e9a67805729f5af3c1796d3db27bce08e"
os = "freebsd"

    [[Cubature.download]]
    sha256 = "2e544d749c0c1b2f3e4437f2b1c02c8b639cf93c79d91f22685c9167a936ef0f"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.x86_64-unknown-freebsd.tar.gz"
[[Cubature]]
arch = "x86_64"
git-tree-sha1 = "20b9acf3830e4cd73923f6f8a48e26be037a78b0"
os = "windows"

    [[Cubature.download]]
    sha256 = "627b2c6e2fc3b2d4ffaa5416f9d2380a4909d6b9b90c46bef2ddcd785fcafc49"
    url = "https://github.com/JuliaBinaryWrappers/Cubature_jll.jl/releases/download/Cubature-v1.0.4+0/Cubature.v1.0.4.x86_64-w64-mingw32.tar.gz"
